### ISSUE TITLE
Link to non existing page

### ISSUE THREAD

**Issue by albinmedoc** [homebridge/homebridge.github.io#40]
### Analysis

There is a link linking to a non existing page 

https://www.jsonschema.net/home

### Expected Behavior

Get linked to and presented with a JSON Schema Tool

### Steps To Reproduce

Visit [Plugin Config Schema](https://developers.homebridge.io/#/config-schema) and scroll down to [Form Generator Playground](https://developers.homebridge.io/#/config-schema#form-generator-playground) and click the linked labeled "JSON Schema Tool"

### Logs

```markdown
Not relevant
```

### Configuration

```json
Not relevant
```

### Environment

Not relevant

### Process Supervisor

not applicable

**Comment by oznu** [comment]
I removed the link. Thanks.
